name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node 12.5.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.5.0

      - name: npm install and npm run build
        run: |
          npm ci
          npm run build:ci 
        working-directory: ./strava-frontend-picture
      
      - name: save files on s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete 
        env:
          AWS_S3_BUCKET: arn:aws:s3:::nicholas-gonzalez.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
          SOURCE_DIR: './strava-frontend-picture/dist/strava-frontend-picture'      # optional: defaults to entire repository
